name: Farm Manager CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Build and push Docker image
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            --tag ${{ secrets.DOCKER_USERNAME }}/farm-manager:latest \
            --push \
            .

      # Deploy on provisioned EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/farm-manager || mkdir ~/farm-manager && cd ~/farm-manager

            # Cleanup old containers/images
            docker system prune -af
            docker volume prune -f

            # Write .env
            echo "${{ secrets.ENV_FILE }}" > .env

            # Copy docker-compose.yml from repo
            cat > docker-compose.yml << 'EOF'
            $(cat docker-compose.yml)
            EOF

            # Start app
            docker compose up -d --remove-orphans
